steps:
  # Build API
  - name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'build',
        '-f',
        'apps/api/Dockerfile.prod',
        '-t',
        'gcr.io/$PROJECT_ID/cloud-api:$COMMIT_SHA',
        '.'
      ]

  # Build Account
  - name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'build',
        '-f',
        'apps/account/Dockerfile.prod',
        '-t',
        'gcr.io/$PROJECT_ID/cloud-account:$COMMIT_SHA',
        '.'
      ]

  # Build Files
  - name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'build',
        '-f',
        'apps/files/Dockerfile.prod',
        '-t',
        'gcr.io/$PROJECT_ID/cloud-files:$COMMIT_SHA',
        '.'
      ]

  # Build Notes
  - name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'build',
        '-f',
        'apps/notes/Dockerfile.prod',
        '-t',
        'gcr.io/$PROJECT_ID/cloud-notes:$COMMIT_SHA',
        '.'
      ]

  # Push images to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/cloud-api:$COMMIT_SHA']

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/cloud-account:$COMMIT_SHA']

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/cloud-files:$COMMIT_SHA']

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/cloud-notes:$COMMIT_SHA']

  # Tag images with 'latest'
  - name: 'gcr.io/cloud-builders/docker'
    args: ['tag', 'gcr.io/$PROJECT_ID/cloud-api:$COMMIT_SHA', 'gcr.io/$PROJECT_ID/cloud-api:latest']

  - name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'tag',
        'gcr.io/$PROJECT_ID/cloud-account:$COMMIT_SHA',
        'gcr.io/$PROJECT_ID/cloud-account:latest'
      ]

  - name: 'gcr.io/cloud-builders/docker'
    args:
      ['tag', 'gcr.io/$PROJECT_ID/cloud-files:$COMMIT_SHA', 'gcr.io/$PROJECT_ID/cloud-files:latest']

  - name: 'gcr.io/cloud-builders/docker'
    args:
      ['tag', 'gcr.io/$PROJECT_ID/cloud-notes:$COMMIT_SHA', 'gcr.io/$PROJECT_ID/cloud-notes:latest']

  # Push latest tags
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/cloud-api:latest']

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/cloud-account:latest']

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/cloud-files:latest']

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/cloud-notes:latest']

images:
  - 'gcr.io/$PROJECT_ID/cloud-api:$COMMIT_SHA'
  - 'gcr.io/$PROJECT_ID/cloud-api:latest'
  - 'gcr.io/$PROJECT_ID/cloud-account:$COMMIT_SHA'
  - 'gcr.io/$PROJECT_ID/cloud-account:latest'
  - 'gcr.io/$PROJECT_ID/cloud-files:$COMMIT_SHA'
  - 'gcr.io/$PROJECT_ID/cloud-files:latest'
  - 'gcr.io/$PROJECT_ID/cloud-notes:$COMMIT_SHA'
  - 'gcr.io/$PROJECT_ID/cloud-notes:latest'

options:
  logging: CLOUD_LOGGING_ONLY
