steps:
  # Build and push all services in parallel with caching
  - name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'build',
        '--cache-from',
        'gcr.io/$PROJECT_ID/cloud-api:latest',
        '-f',
        'apps/api/Dockerfile.cloudrun',
        '-t',
        'gcr.io/$PROJECT_ID/cloud-api:latest',
        '.'
      ]
    id: 'build-api'
  - name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'build',
        '--cache-from',
        'gcr.io/$PROJECT_ID/cloud-account:latest',
        '-f',
        'apps/account/Dockerfile.cloudrun',
        '-t',
        'gcr.io/$PROJECT_ID/cloud-account:latest',
        '.'
      ]
    id: 'build-account'
  - name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'build',
        '--cache-from',
        'gcr.io/$PROJECT_ID/cloud-files:latest',
        '-f',
        'apps/files/Dockerfile.cloudrun',
        '-t',
        'gcr.io/$PROJECT_ID/cloud-files:latest',
        '.'
      ]
    id: 'build-files'
  - name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'build',
        '--cache-from',
        'gcr.io/$PROJECT_ID/cloud-notes:latest',
        '-f',
        'apps/notes/Dockerfile.cloudrun',
        '-t',
        'gcr.io/$PROJECT_ID/cloud-notes:latest',
        '.'
      ]
    id: 'build-notes'

  # Push all images
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/cloud-api:latest']
    waitFor: ['build-api']
    id: 'push-api'
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/cloud-account:latest']
    waitFor: ['build-account']
    id: 'push-account'
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/cloud-files:latest']
    waitFor: ['build-files']
    id: 'push-files'
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/cloud-notes:latest']
    waitFor: ['build-notes']
    id: 'push-notes'

  # Deploy API service first
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      [
        'run',
        'deploy',
        'cloud-api',
        '--image',
        'gcr.io/$PROJECT_ID/cloud-api:latest',
        '--region',
        'us-central1',
        '--platform',
        'managed',
        '--allow-unauthenticated',
        '--memory',
        '512Mi',
        '--cpu',
        '1',
        '--max-instances',
        '10'
      ]
    waitFor: ['push-api']
    id: 'deploy-api'

  # Deploy frontend services with API URL
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      [
        'run',
        'deploy',
        'cloud-account',
        '--image',
        'gcr.io/$PROJECT_ID/cloud-account:latest',
        '--region',
        'us-central1',
        '--platform',
        'managed',
        '--allow-unauthenticated',
        '--memory',
        '512Mi',
        '--cpu',
        '1',
        '--max-instances',
        '10'
      ]
    waitFor: ['push-account', 'deploy-api']

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      [
        'run',
        'deploy',
        'cloud-files',
        '--image',
        'gcr.io/$PROJECT_ID/cloud-files:latest',
        '--region',
        'us-central1',
        '--platform',
        'managed',
        '--allow-unauthenticated',
        '--memory',
        '512Mi',
        '--cpu',
        '1',
        '--max-instances',
        '10'
      ]
    waitFor: ['push-files', 'deploy-api']

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      [
        'run',
        'deploy',
        'cloud-notes',
        '--image',
        'gcr.io/$PROJECT_ID/cloud-notes:latest',
        '--region',
        'us-central1',
        '--platform',
        'managed',
        '--allow-unauthenticated',
        '--memory',
        '512Mi',
        '--cpu',
        '1',
        '--max-instances',
        '10'
      ]
    waitFor: ['push-notes', 'deploy-api']

options:
  logging: CLOUD_LOGGING_ONLY
  machineType: 'E2_HIGHCPU_8'
  diskSizeGb: '100'

timeout: '3600s'

images:
  - 'gcr.io/$PROJECT_ID/cloud-api:latest'
  - 'gcr.io/$PROJECT_ID/cloud-account:latest'
  - 'gcr.io/$PROJECT_ID/cloud-files:latest'
  - 'gcr.io/$PROJECT_ID/cloud-notes:latest'
