services:
  postgres:
    image: postgres:15
    container_name: cloud-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: cloud
    ports:
      - '5432:5432'
    volumes:
      - cloud-postgres-data:/var/lib/postgresql/data
    restart: unless-stopped
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres']
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  cloud-postgres-data:
