services:
  traefik:
    image: traefik:v2.10
    container_name: traefik
    command:
      - --api.insecure=true
      - --providers.docker=true
      - --entrypoints.web.address=:80
    ports:
      - '80:80'
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  postgres:
    image: postgres:15
    container_name: myapp-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: myapp
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

  api:
    build:
      context: ./apps/api
      dockerfile: Dockerfile
    container_name: myapp-api
    depends_on:
      - postgres
    environment:
      DATABASE_URL: postgres://postgres:postgres@postgres:5432/myapp
      FILE_ENCRYPTION_KEY: 0123456789abcdef0123456789abcdef
      PORT: 8000
    working_dir: /app
    restart: unless-stopped
    volumes:
      - storage_data:/app/storage
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.api.rule=Host(`api.localhost`)'
      - 'traefik.http.services.api.loadbalancer.server.port=8000'

  dashboard:
    image: node:20-alpine
    container_name: myapp-dashboard
    working_dir: /app
    volumes:
      - ./apps/dashboard:/app
    command: sh -c "npm install && npm run dev"
    environment:
      - NODE_ENV=development
    restart: unless-stopped
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.dashboard.rule=Host(`dashboard.localhost`)'
      - 'traefik.http.services.dashboard.loadbalancer.server.port=3000'

volumes:
  postgres_data:
  storage_data:
