services:
  postgres:
    image: postgres:15
    container_name: myapp-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: myapp
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

  api:
    build:
      context: ./apps/api
      dockerfile: Dockerfile
    container_name: myapp-api
    depends_on:
      - postgres
    environment:
      DATABASE_URL: postgres://postgres:postgres@postgres:5432/myapp
      FILE_ENCRYPTION_KEY: 0123456789abcdef0123456789abcdef
      PORT: 8000
    ports:
      - '8000:8000'
    working_dir: /app
    restart: unless-stopped
    volumes:
      - storage_data:/app/storage

volumes:
  postgres_data:
  storage_data:
