services:
  account:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        APP: account
    working_dir: /repo
    volumes:
      - ./:/repo
    ports:
      - '3001:3000'
    environment:
      - PORT=3000

  dashboard:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        APP: dashboard
    working_dir: /repo
    volumes:
      - ./:/repo
    ports:
      - '3002:3000'
    environment:
      - PORT=3000

  api:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        APP: api
    working_dir: /repo
    volumes:
      - ./:/repo
    ports:
      - '4000:4000'
    environment:
      - PORT=4000
    depends_on:
      - postgres

  nginx:
    image: nginx:latest
    ports:
      - '80:80'
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - account
      - dashboard
      - api

  postgres:
    image: postgres:16-alpine
    restart: unless-stopped
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=cloud
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  node_modules_account:
  node_modules_dashboard:
  node_modules_api:
  postgres_data:
